### ISSUE TITLE
Error: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by electroblep** [Maurdekye/training-picker#16]
Please cover these three things in your report:
* What exactly is wrong
I get this error message when I click "extract frames":   Error: module 'ffmpeg' has no attribute 'input'

You can also optionally provide these details if you think it'll help me figure out the issue faster:
* Operating system :   win 10
* Browser :  Edge
* Any error messages or logs, if applicable : Error: module 'ffmpeg' has no attribute 'input'
Someone on reddit said I may not have ffmpeg installed in the right directory. I have the exe sitting in the same folder as A1111 webuser.bin file, so I'm not really sure where else to put it. So I'm not sure if it's a bug in the training picker, or soemthing going on with ffmpeg, but there are no instructions in this git that says anything other than just to install it.

**Comment by Maurdekye** [comment]
This issue occurs if you have the wrong python library for ffmpeg installed; see https://github.com/Maurdekye/training-picker/issues/6
