### ISSUE TITLE
ImportError: cannot import name 'folder_symbol' from 'modules.ui'

### ISSUE THREAD

**Issue by Harvester62** [Maurdekye/training-picker#21]
Please cover these three things in your report:
* What exactly is wrong
After the latest git pull of the SDWUI (Commit hash: 194cbd065e4644e986889b78a5a949e075b610e8) I get the following error in the console (see below)

* How to recreate the problem
Simply update SDWUI and run the webui-user.bat file

* What you expected to happen vs what actually happened
It worked until yesterday.

You can also optionally provide these details if you think it'll help me figure out the issue faster:

* Operating system
Windows Pro 64bit (32GB RAM)

* Browser
Firefox v109.0

* Any error messages or logs, if applicable

Error loading script: training_picker.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\training-picker\scripts\training_picker.py", line 16, in <module>
    from modules.ui import create_refresh_button, folder_symbol
ImportError: cannot import name 'folder_symbol' from 'modules.ui' (C:\stable-diffusion-webui\modules\ui.py)

* Particular details about how you installed the extension or other relevant software
It was installed via the SDWUI Extensions interface several months ago.

* Screenshots demonstrating the issue
(not needed, see the above Traceback error message)

**Comment by GiusTex** [comment]
Same problem

**Comment by Harvester62** [comment]
Thank  you @GiusTex for your fix. I don't really use many of the SDWUI extensions but I need them to be installed and activated to be able to localize their UI in Italian. 
So, I do hope that @Maurdekye will find the time to officially fix this problem. 
Furthermore, I noticed that the two buttons to the upper right are displayed behind the text box and the texts of the buttons are not visible (see attached screenshot). 

Thank you again and I look forward for it to be officially fixed.
![immagine](https://user-images.githubusercontent.com/29801031/214649551-5bccd0cd-096b-445e-959c-eb56153f7f90.png)

**Comment by itsdotscience** [comment]
This fixed the error and made the extension option appear properly in the UI. Taken from latest automatic1111 git, not setup atm to commit, traveling. Hope this gets ya'll further! :)

```
diff --git a/modules/ui.py b/modules/ui.py
index 85ae62c..79e372f 100644
--- a/modules/ui.py
+++ b/modules/ui.py
+folder_symbol = '\U0001F4C1' # 📁
apply_style_symbol = '\U0001f4cb' # 📋
clear_prompt_symbol = '\U0001F5D1' # 🗑️
extra_networks_symbol = '\U0001F3B4' # 🎴
```
attached as text file as well. Matched to the folder icon visible on the text2img page for consistency. 

[ui.py_patch_add_folder_unicode_symbol.txt](https://github.com/Maurdekye/training-picker/files/10513434/ui.py_patch_add_folder_unicode_symbol.txt)

**Comment by cheezecrisp** [comment]
> ~This fixed the error and made the extension option appear properly in the UI. Taken from latest automatic1111 git, not setup atm to commit, traveling. Hope this gets ya'll further! :)~
> 
> Ah, disregard...seems it just lives in ui_common.py
> 
> so..
> 
> `from modules.ui_common import folder_symbol `

Tried so and the extension UI loads successfully but could not load viedo files. the dropdown menu of video is empty even there are videos in 'videos' folder. Refresh buttom also has no effect.

**Comment by itsdotscience** [comment]
Where are you storing the videos? When I first got it going it wasn't immediately apparent that they go in

`stable-diffusion-webui/training-picker/videos`
and not 
`stable-diffusion-webui/extensions/training-picker/videos`

Of course in the Settings tab under Training Picker you can change this location to wherever. 

Hope that helps!

-IDS

**Comment by cheezecrisp** [comment]
> Where are you storing the videos? When I first got it going it wasn't immediately apparent that they go in
> 
> `stable-diffusion-webui/training-picker/videos` and not `stable-diffusion-webui/extensions/training-picker/videos`
> 
> Of course in the Settings tab under Training Picker you can change this location to wherever.
> 
> Hope that helps!
> 
> -IDS

The path is exactly 

> stable-diffusion-webui/training-picker/videos

**Comment by itsdotscience** [comment]
> > Where are you storing the videos? When I first got it going it wasn't immediately apparent that they go in
> > `stable-diffusion-webui/training-picker/videos` and not `stable-diffusion-webui/extensions/training-picker/videos`
> > Of course in the Settings tab under Training Picker you can change this location to wherever.
> > Hope that helps!
> > -IDS
> 
> The path is exactly `stable-diffusion-webui/training-picker/videos`

Ah, I'm using absolute paths, drop the `stable-diffusion-webui/` part and it should work

**Comment by rockerBOO** [comment]
I do not plan on supporting this further, but made a fork for the meantime for this bug. I have filed a pull request, #23,  that fixes the OP bug and cleans up the UI a little bit. 

Can install this as an extension: https://github.com/rockerBOO/training-picker

**Comment by Harvester62** [comment]
Thank you @rockerBOO for the PR and fixing this issue. What do you mean when you say that you "do not plan on supporting this further." ? Do you mean that you will no longer contribute to this project, for any reasons? Not that the author @Maurdekye  of this extension will no longer support it, right? Thank you.

**Comment by rockerBOO** [comment]
Well, I meant to say that I wasn't going to maintain a fork, and was just a temporary thing for people to be able to install and use this. Also, that it was not my intention of supporting (maintaining) a fork. Would rather @Maurdekye continue to develop this when they have the chance. Thank you.

**Comment by Harvester62** [comment]
Ah, understood. Thank you.

**Comment by coronet1127** [comment]
Resolved.

The folder_symbol is now in modules.ui_common

trainingpicker/scripts/training_picker.py
-----------------------------------------------------------------
from modules.ui import create_refresh_button, folder_symbol
↓
from modules.ui import create_refresh_button
from modules.ui_common import folder_symbol
-------------------------------------------------------------------
Fixes
