### ISSUE TITLE
Automatic1111 1.2.1 - No longer get the red crop box

### ISSUE THREAD

**Issue by steploff** [Maurdekye/training-picker#32]
I downloaded the new Automatic1111 - version 1.2.1 and don't get the red crop box anymore for this extension.

**Comment by hornedpariah** [comment]
I am having the same issue, im going bonkers XD

**Comment by Mistborn-First-Era** [comment]
Same problem

**Comment by dicksensei69** [comment]
I think everyone is having the problem. Anyone have a solution yet?

**Comment by pagran** [comment]
> I think everyone is having the problem. Anyone have a solution yet?

https://github.com/Maurdekye/training-picker/pull/33
