### ISSUE TITLE
Error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Ev-Bro** [Maurdekye/training-picker#4]
When I run the extension, it says Error: [WinError 2] The system cannot find the file specified. It creates an empty folder. If I try to run again, it says there is already a folder there and that I can delete it if I want. 

Thank you.

**Comment by Maurdekye** [comment]
Make sure you have ffmpeg installed, and/or reinstall it. Then attempt to use the extension again and update me here.

**Comment by Ev-Bro** [comment]
Thanks for the reply. I deleted, then reinstalled ffmpeg, Same behavior for me. 

Error: [WinError 2] The system cannot find the file specified

Frame set already exists at ... \training-picker\extracted-frames\movie! Delete the folder first if you would like to recreate it.

**Comment by Ev-Bro** [comment]
Ok, I got it to work by dragging ffmpeg.exe to the root of my stable diffusion install dir. Thanks!

**Comment by Maurdekye** [comment]
Glad to hear it!
