### ISSUE TITLE
array of frame viewer is weird

### ISSUE THREAD

**Issue by wansf3** [Maurdekye/training-picker#5]
it is not sorted by file name normally like 01.png -> 02.png -> 03.png etc,
say if i want to pick 513.png but typing "513" in viewer does not present 513.png,
also could u please make frames load faster in the viewer? 1 sec lag while loading next frame is kinda time consuming , thanks

**Comment by Maurdekye** [comment]
You bring up a good point, thanks for catching that. Also, these are two separate issues, a bug report and a feature request. Do you mind making two separate tickets for each one instead of putting them both in this one? I'll consider this to be the bug report.

**Comment by wansf3** [comment]
its still bugged , the first 1~10 frames are fine but when i go to frame 11, it jump to100.png , and everything after that are padded up randomly , for example frame 19 = 108.png , frame 55 = 140.png etc, hence i still cannot directly type in the number of .png i want into the viewer, and they are not stay in correct order anyway.
