### ISSUE TITLE
load faster in frame viewer

### ISSUE THREAD

**Issue by wansf3** [Maurdekye/training-picker#7]
there is a huge lag when browsing frames , going to next frame has almost 1 second loading time which is very annoying
could you please make it work like normal photo viewer apps?

**Comment by Maurdekye** [comment]
The tradeoff here would be either a small loading time in between each frame, or a long, several-minute loading time when you select a new frame set, as it has to load all the images in at once. 
I'm experimenting with a caching system to hopefully alleviate some of the latency, but gradio is pretty limiting in how you can cache image data on the clientside. I might have to come back to this in the future and do something hacky.

**Comment by Maurdekye** [comment]
For now this is a fairly low priority feature implement. If someone else wants to come along and make progress on it, i'd gladly review a PR.

**Comment by wansf3** [comment]
i think its pretty good now, from 1.X lag to 0.1~0.2ish , thx
