### ISSUE TITLE
Error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by WlnterW** [Maurdekye/training-picker#9]
When trying to load a video in the extension I get the Error message "Error: [WinError 2] The system cannot find the file specified".
The output folder is generated with the name of the input video but after that nothing happens.
I installed the extension via the Automatic1111 webui and also tried a manual install.

The videos are located in the folder which is opened by the button. They are in mp4 format.

**Comment by WlnterW** [comment]
I installed it using the git clone command on their website through the webui-user.bat
Ffmpeg is installed in the stable-diffusion-webui folder.
Do I have to set paths manually? And if so where would I start?

**Comment by Maurdekye** [comment]
Visit ffmpeg's website at https://ffmpeg.org/ and download the executable installers for your OS, I'm assuming Windows. That should automatically add ffmpeg to your path.
Show me a screenshot of where you have ffmpeg installed, that should help clear up any confusion.

**Comment by WlnterW** [comment]
Thank you! Got it to work in the end. 
I could not find a installer for ffmpeg but [this video](https://youtu.be/IECI72XEox0?t=276) helped me to set it up properly.

**Comment by Maurdekye** [comment]
Awesome!
